### ISSUE TITLE
Patching Guide?

### ISSUE THREAD

**Issue by hexvalid** [pouyadarabi/Instagram_SSL_Pinning#1]
Hi
How can I patch libliger.so of another Instagram version.

Do you have a patch file?

Thanks

**Comment by pouyadarabi** [comment]
Hi,

You need to find verifier function
for this version it was `verifyWithMetrics` offset 0x000AA950, 0x000AA952 

Older versions may have used another method to verify ssl certificate in native or android layer

**Comment by hexvalid** [comment]
I ill try this. 
Thanks!
