### ISSUE TITLE
SSL Pinning

### ISSUE THREAD

**Issue by wendal2841** [pouyadarabi/Instagram_SSL_Pinning#10]
I downloaded 
https://github.com/pouyadarabi/Instagram_SSL_Pinning/tree/master/arm

began to catch requests through charlize

http://ibb.co/cShCS7

after replaced the file libliger.so 
/data/data/com.instagram.android/lib/

requests disappeared after that, Charlize no longer sees

**Comment by wendal2841** [comment]
The second question is, how can I get IG_SIG_KEY?

**Comment by Githubplay12** [comment]
I will answer both :

1. Just use the apk provided by pouya, it works 100 %
2. Available in the internet (save the script ;))

**Comment by IvanMMM** [comment]
Same for me. v35 refuses to work with your liblinger.so and Charles.
[This is repacked file](https://www.dropbox.com/s/ej9sry4xiv8bbwc/com.instagram.android_35.0.0.20.96-95414346_minAPI16%28armeabi-v7a%29%28280%2C360%2C400%2C420%2C480%2C560%2C640dpi%29_apkmirror.com_repacked.apk?dl=0) with your liblionger.so and patched .xml for Android 7.0+, can you please check if it's working on your environment?

**Comment by pouyadarabi** [comment]
@Githubplay12 👍
@IvanMMM Your APK not worked on my device

I've uploaded an APK for version 35.0.0.20.96
Tested on non-rooted Android Oreo and Lollipop

**Comment by wendal2841** [comment]
Is it possible to get IG_SIG_KEY from the latest version?

**Comment by pouyadarabi** [comment]
Noting is impossible.
But This repository is for SSL Pinning not for Instagram key
