### ISSUE TITLE
Fork for APK v27, to match "Instagram-API" project

### ISSUE THREAD

**Issue by milsss** [pouyadarabi/Instagram_SSL_Pinning#12]
Hi,

Firstly, thank you for the repo.

One of the biggest IG projects on github is [Instagram-API](https://github.com/mgp25/Instagram-API), and it is pinned to IG v27. 
It would be very useful for testing purposes to be able to work with the same version of the app as the API uses. Would it be possible to create a fork of the code for v27 of IG? I don't think I have the skills to do this myself.

Thanks

**Comment by pouyadarabi** [comment]
Hi,

I created a patch for version 26
endpoints and data shouldn't be different

I haven't enough time to create patch for old versions
