### ISSUE TITLE
Ssl un pinning 

### ISSUE THREAD

**Issue by wendal2841** [pouyadarabi/Instagram_SSL_Pinning#14]
in instagram, pinning only libliger.so ?

![image](https://user-images.githubusercontent.com/27301672/40124063-5677d4bc-5930-11e8-8ac7-d6e09cecc433.png)

**Comment by wendal2841** [comment]
here I cut the test, they added it somewhere else, can tell where it still is?

**Comment by wendal2841** [comment]
everything works fine

**Comment by learn-itnow** [comment]
@wendal2841 can you help me to SSL unpin instagram app? It looks like you have already done that.
