### ISSUE TITLE
Frida

### ISSUE THREAD

**Issue by GHXST01** [pouyadarabi/Instagram_SSL_Pinning#15]
Hey, I'd like to create a dynamic patch using Frida.
Do you have an article / write up explaining your patch?

**Comment by GHXST01** [comment]
@pouyadarabi are you still available? I'm the creator of the following patch using Frida:

```
var moduleNames  = ['libxliger.so', 'libsslx.so'];
var functionName = 'X509_verify_cert'

moduleNames.forEach( function(moduleName) {

    Interceptor.attach(Module.findExportByName(moduleName, functionName), {

        onEnter: function (args) {
            // Logging the progress
            send('');
        },

        onLeave: function (retval) {
            // Patching return value from 0x0 -> 0x1
            retval.replace(1);
        }

    });

});
```

Can you tell me if you've updated anything besides this? I want to update my patch to work with the latest IG versions.

**Comment by GHXST01** [comment]
@pouyadarabi Hey, could you please get back to me? Thanks.

**Comment by pouyadarabi** [comment]
Hi,

Just **libliger.so** and **X509_verify_cert**

**Comment by unlimire** [comment]
@pouyadarabi but i got expected a pointer

**Comment by hekahatika** [comment]
@pouyadarabi libliger.so  dont have function "X509_verify_cert"
can you send me this pic https://raw.githubusercontent.com/pouyadarabi/Instagram_SSL_Pinning/master/arm/after.jpg?123
you deleted it

**Comment by SuhatAkbulak** [comment]
Is there any improvement on the latest version?
Read the Data of the Latest Version.
I can give you a tip :)

**Comment by gaplan** [comment]
libcrypto.so has X509_verify_cert function.
Thanx frida.

__handlers__/libcrypto.so/X509_verify_cert.js

**Comment by SuhatAkbulak** [comment]
@gaplan last version ?

**Comment by gaplan** [comment]
@SuhatAkbulak V75 & v76 (alpha)
but does not running on this.
not calling for Ssl cert

**Comment by SuhatAkbulak** [comment]
@gaplan What version does it work on?

**Comment by gaplan** [comment]
@SuhatAkbulak  i dunno, 
i'll try older versions.
(yenilerinde bu yok. arıyorum yerini)

**Comment by SuhatAkbulak** [comment]
@gaplan Şener Şen ❤️

**Comment by SuhatAkbulak** [comment]
@gaplan pls add your skype 
Skype=instabayi

**Comment by gaplan** [comment]
@SuhatAkbulak 
I'm going to take out all the keys.
Soon.

**Comment by SuhatAkbulak** [comment]
@gaplan please contact me

**Comment by gokaybiz** [comment]
Suhat naber?

**Comment by SuhatAkbulak** [comment]
@gokaybiz Sizleri sormalı

**Comment by forbes-100** [comment]
Guys, I posted a normal version look in my profile, enough to suffer.

**Comment by gokaybiz** [comment]
Are u inspired from whitehat mode?
I mean, are u cracked that feature? Or something else?
