### ISSUE TITLE
Doesn't work completely 

### ISSUE THREAD

**Issue by learn-itnow** [pouyadarabi/Instagram_SSL_Pinning#16]
I tried the patched apk 35.0.0.20.96 that you provided

It's works on https://b.i.instagram.com/

But it doesn't work on https://i.instagram.com/

replacing lib file on Version 44.0.0.9.93 on rooted phone i can't make it works.

**Comment by pouyadarabi** [comment]
patch working fine!
check perm + certificate and wait

**Comment by learn-itnow** [comment]
@pouyadarabi  just let me know if this is working on https://i.instagram.com/ or not?
