### ISSUE TITLE
ssl pinning for v 10.8.0

### ISSUE THREAD

**Issue by hesam67b** [pouyadarabi/Instagram_SSL_Pinning#17]
Hello.
i'm from iran.
can you help me for ssl pinning for v10.8.0 ??
how can i contact with you??

**Comment by pouyadarabi** [comment]
salam

tuye un version ha momkene ssl pining dar sathe native anjam nashode bashe
ba xposed framework check kon bebin javab mide ya na

**Comment by hesam67b** [comment]
salam. check kardam nemishe. donbale ye rahe hal vase sakhte account ba kefiat hastam. mesle inke vaghan dare dar app instagram sakhte mishe. mitoni komakam koni??

**Comment by bob7chance** [comment]
@pouyadarabi 
hi, can you update ssl_pinning for Instagram v.51.0.0.9.85 or higher?
and upload patched apk
Please

p.s. can you see ssl_pinning for app IGTV v50.0.0.41.119 (on apkmirror)?

**Comment by prateek-resiliencesoft** [comment]
@pouyadarabi 
Hi, Do you have latest version ssl unpinned file?

Thanks
