### ISSUE TITLE
Patch 51.0.0.20.85

### ISSUE THREAD

**Issue by ramtinak** [pouyadarabi/Instagram_SSL_Pinning#18]
Hi,
Is it possible to patch latest version of IG (51.0.0.20.85)?
It would be helpful.

**Comment by vurgun1** [comment]
I tried but not possible.

**Comment by ramtinak** [comment]
@vurgun1 do you have any newer version? Newer than 35?

**Comment by ghost** [comment]
Has anyone succeeded patching latest version?

Is is not possible or slightly different?

**Comment by vurgun1** [comment]
@pouyadarabi

**Comment by readak** [comment]
I did patched new version 52.0.0.8.83 (x86) libliger.so
Download: 

[v_packed_52.0.0.8.83_libliger.zip](https://github.com/pouyadarabi/Instagram_SSL_Pinning/files/2184509/v_packed_52.0.0.8.83_libliger.zip)

**Comment by bagez** [comment]
Thanks you for sharing!

I am trying to patch myself (ARM), it works on b.i.instagram.com, but not on i.instagram.com. Have you faced the same problem?

**Comment by prateek-resiliencesoft** [comment]
@vurgun1 
Hi do you new version APK that have disable SSL Unpinning.

**Comment by irfan798** [comment]
@readak So im using genymotion Google Nexus 5 6.0.0 API23
And charles proxy
I setted up ssl proxying so i can watch all request from https sites

installed instagram 52.0.0.8.83 (x86) stopped it
Then pushed your libliger.so to /data/data/com.instagram.android/lib/libliger.so
then 
`chown system /data/data/com.instagram.android/lib/libliger.so `
`chgrp system /data/data/com.instagram.android/lib/libliger.so `
`chmod 755 /data/data/com.instagram.android/lib/libliger.so `
So it has now same permissions with original file
When i start instagram its all unkown_ca
![image](https://user-images.githubusercontent.com/6182106/42735421-33f088f2-885c-11e8-8842-a6a0879524c0.png)

Also tried with Version 44.0.0.9.93 with no luck

I only see requests when i patch version 35.0.0.20.96

Did i missed a step?

**Comment by readak** [comment]
APK'i kurduktan sonra değil APK'i compile ederken .so dosyasını değiştirmelisin.

**Comment by irfan798** [comment]
@readak Onu da denedim apktool ile decopile edip sonra libligeri degiştirdim tekrar apktool ile compile ettim kendi oluşturduğum self signed ile signladım yine aynı sonucu verdi
Signing kısmında farklı bir şey mi yapmam gerekiyor?

**Comment by readak** [comment]
Ekstra hiçbşy yapmıyorum ama Charless yerine Fiddler deneyebilirsin. Belki onunla alakalı bir sorun olabilir. Sonuç olarak sadece "b.i.instagram.com" çalışıyor. Oda APK açıldığında yeni 5-6 istek gönderiyor. Önemli olan "i.instagram.com" henüz aşamadım. Bir değişiklik olursa APK ile birlikte burada paylaşıcam.

**Comment by irfan798** [comment]
Anladım compile ettikten sonra signlarken ne kullandığımızın bir önemi yok o zaman?

**Comment by readak** [comment]
APK Tool ilk sign'i kullanıyor. Orjinal haline çeviriyor

**Comment by maximtart** [comment]
@bagez Hi I have the same.
Did you found a solution?

**Comment by learn-itnow** [comment]
will this patch work on https://i.instagram.com/ as well?

**Comment by bagez** [comment]
No... has anyone succeeded to patch https://i.instagram.com on the latest version?

**Comment by EphramDoyle** [comment]
Has anyone been able to patch it?

**Comment by learn-itnow** [comment]
@readak will your patch work on  https://i.instagram.com as well?

**Comment by EphramDoyle** [comment]
@readak 
> I did patched new version 52.0.0.8.83 (x86) libliger.so
Download: v_packed_52.0.0.8.83_libliger.zip

I've tried it but it does not work for me:
https://imgur.com/a/QXuWt8d

I want to read the requests to the new question sticker. Does anyone have a patched version that works properly? Thanks!

**Comment by spaitnet** [comment]
Has anyone been able to patch it?

**Comment by delmotte** [comment]
up

**Comment by AmaHacka** [comment]
> 
> 
> Thanks you for sharing!
> 
> I am trying to patch myself (ARM), it works on b.i.instagram.com, but not on i.instagram.com. Have you faced the same problem?



> 
> 
> Thanks you for sharing!
> 
> I am trying to patch myself (ARM), it works on b.i.instagram.com, but not on i.instagram.com. Have you faced the same problem?

Can you show and describe your patch?

**Comment by Insayt** [comment]
up

**Comment by huseyinalp-zz** [comment]
@readak veya @irfan798  bu konuda herhangi bir gelişme sağladınız mı?

**Comment by votanhung** [comment]
> I did patched new version 52.0.0.8.83 (x86) libliger.so
> Download:
> 
> [v_packed_52.0.0.8.83_libliger.zip](https://github.com/pouyadarabi/Instagram_SSL_Pinning/files/2184509/v_packed_52.0.0.8.83_libliger.zip)

how to unpack file  libliger
