### ISSUE TITLE
Patch 68

### ISSUE THREAD

**Issue by pankixoi2113** [pouyadarabi/Instagram_SSL_Pinning#21]
Does anyone have patched apk with this version?

**Comment by dakiesse** [comment]
up

**Comment by dakiesse** [comment]
@pankixoi2113 did you find something?

**Comment by bravepuzzle** [comment]
@pouyadarabi any chance you could update the latest version? thanks.

**Comment by pouyadarabi** [comment]
Duplicate of #23
