### ISSUE TITLE
Any suggestions for 70.0.0.22.98

### ISSUE THREAD

**Issue by AmaHacka** [pouyadarabi/Instagram_SSL_Pinning#23]
I've patched libliger.so for version 70.0.0.22.98 but still unable to see traffic
![capture](https://user-images.githubusercontent.com/22823988/48343694-19ef8800-e684-11e8-8839-4b3a1f819b72.PNG)
Maybe yo have any suggestions how fix it?

**Comment by housedir** [comment]
I also could not capture after patching :(

**Comment by pokeefer** [comment]
Yeah same here.  Maybe Instagram added pinning in another function of libliger.so file. Also what program did you use to decompile the so file into the code above?

**Comment by dariolourenco** [comment]
@pokeefer its a screenshot from IDA

**Comment by abutizi** [comment]
same here :(

**Comment by S00164379** [comment]
> I've patched libliger.so for version 70.0.0.22.98 but still unable to see traffic
> ![capture](https://user-images.githubusercontent.com/22823988/48343694-19ef8800-e684-11e8-8839-4b3a1f819b72.PNG)
> Maybe yo have any suggestions how fix it?

Did you find anything?

**Comment by AmaHacka** [comment]
@S00164379 Nope :(

**Comment by SuhatAkbulak** [comment]
Is there something?

**Comment by NGame1** [comment]
is there any success?

**Comment by seva0812** [comment]
Selling
Instagram 75 version pinning ssl key signed
skype: webqart_1

**Comment by oliverbytes** [comment]
> Selling
> Instagram 75 version pinning ssl key signed
> skype: webqart_1

how much?

**Comment by pouyadarabi** [comment]
I think they created a custom ssl pinning in android layer :-\

**Comment by pouyadarabi** [comment]
> > I think they created a custom ssl pinning in android layer :-\
> 
> I solve this problem

this is a open source repository for researchers 
if you do it just share it publicly

I will create a new patch when I have free time in the next month :-)

**Comment by oliverbytes** [comment]
@pouyadarabi I agree. Hopefully we can all benefit. Thanks a lot

**Comment by hardcoder80** [comment]
> > > I think they created a custom ssl pinning in android layer :-\
> > 
> > 
> > I solve this problem
> 
> this is a open source repository for researchers
> if you do it just share it publicly
> 
> I will create a new patch when I have free time in the next month :-)

There will be no next patch because facebook has fully implemented tls 1.3 in its apps which cannot be decrypted or sniffed, i have spent many hours reversing the 78.0 version and cannot find a solution for tls 1.3

**Comment by tsarpaul** [comment]
> 
> 
> > > > I think they created a custom ssl pinning in android layer :-\
> > > 
> > > 
> > > I solve this problem
> > 
> > 
> > this is a open source repository for researchers
> > if you do it just share it publicly
> > I will create a new patch when I have free time in the next month :-)
> 
> There will be no next patch because facebook has fully implemented tls 1.3 in its apps which cannot be decrypted or sniffed, i have spent many hours reversing the 78.0 version and cannot find a solution for tls 1.3

https://www.imperialviolet.org/2018/03/10/tls13.html

I do wonder which proxies do support TLS 1.3

**Comment by MarcoG3** [comment]
I've written a step-by-step tutorial on how to circumvent Instagram SSL pinning protection on latest APK (v78): https://plainsec.org/how-to-bypass-instagram-ssl-pinning-on-android-v78

Enjoy!

**Comment by oliverbytes** [comment]
Super amazing @marco thanks a lot for your very detailed tutorial.

**Comment by NGame1** [comment]
Hi and thanks to @MarcoG3 for the tutorial. Sorry but I'm not familiar at all with Android. is it possible to someone post the patched APK here  + if any other file needed?

**Comment by pashmak73** [comment]
@MarcoG3
Thanks, but I did everything you did with no success.
Still can’t read all requests.
here is my patched file: [libliger 78.0.0.11.104.zip](https://github.com/pouyadarabi/Instagram_SSL_Pinning/files/2848285/libliger.78.0.0.11.104.zip)

**Comment by shadowzoom** [comment]
Can somebody please upload unsigned instagram apk? Thank. Tried to decode it in 3 days, without luck...

**Comment by RowanFazio** [comment]
> > > I think they created a custom ssl pinning in android layer :-\
> > 
> > 
> > I solve this problem
> 
> this is a open source repository for researchers
> if you do it just share it publicly
> 
> I will create a new patch when I have free time in the next month :-)

We are still waiting!

**Comment by tsarpaul** [comment]
https://github.com/tsarpaul/FBUnpinner
Should work for Instagram.
Replace lib-xzs/libcoldstart.so with lib-zstd/libliger.so

**Comment by AmaHacka** [comment]
@RowanFazio @shadowzoom Check out guys, newest version of IG, Facebook and Facebook Messenger contains option that allows you to disable SSL-pinning and use your SSL-certificate to decrypt HTTP-traffic ^_^

**Comment by pashmak73** [comment]
@AmaHacka can you show us how to do that?

**Comment by AmaHacka** [comment]
1. https://thehackernews.com/2019/03/facebook-whitehat-setting-hackers.html
2. https://www.anonews.co/how-to-enable-facebooks-new-white-hat-researcher-settings/
@pashmak73 @RowanFazio @shadowzoom @housedir @pokeefer

**Comment by oliverbytes** [comment]
Has anyone tried Facebook's new method? I can't seem to make them work on my Android. I've enabled all the settings. I've added the IP of my computer as the proxy in the FB App's Proxy Setting and also tried on the wifi settings. but don't get any traffic.

**Comment by AmaHacka** [comment]
@nemoryoliver go to https://www.facebook.com/whitehat/researcher-settings

**Comment by AmaHacka** [comment]
@nemoryoliver Yep, everything works. Try to reproduce all steps from manual carefully and update your FB app.
