### ISSUE TITLE
HOW TO UNPACK *.SO

### ISSUE THREAD

**Issue by votanhung** [pouyadarabi/Instagram_SSL_Pinning#27]
plz, share method by pass file *.so

**Comment by tsarpaul** [comment]
> Selling
> Instagram 77 version pinning ssl key signed
> Instagram register accounts
> skype: amarvaran
> Telegram: @amarvaran

I usually don't like to pay for my malware.

**Comment by EphramDoyle** [comment]
Use Ida Pro to edit file *.so

**Comment by votanhung** [comment]
thanks,
how to find address need change?
