### ISSUE TITLE
Someone has the latest apk patch?

### ISSUE THREAD

**Issue by knife-s** [pouyadarabi/Instagram_SSL_Pinning#28]
I'm looking for the patched APK where the "hide posts" options are available.
Thanks in advanced

**Comment by amirrezasalimi** [comment]
up

**Comment by forbes-100** [comment]
Guys, I posted a normal version look in my profile, enough to suffer.

**Comment by bolds07** [comment]
could you provide a newer apk please!!!

**Comment by FAlbanni** [comment]
bump

**Comment by ghost** [comment]
bump
