### ISSUE TITLE
Updated APK?

### ISSUE THREAD

**Issue by AlecAnthonyGarcia** [pouyadarabi/Instagram_SSL_Pinning#3]
First off, excellent work with this repo.

Would it be possible for you to update the patched APK to the newest Instagram version (25)?

Or, could you tell me which program you used to decompile and patch the libliger.so file? I see your Burp screenshot is on Mac and I am using Mac, so can you recommend any decompiler for Mac?

Thanks!

**Comment by pouyadarabi** [comment]
Repo updated!
I use IDA decompiler on Mac.

follow steps mentioned in this article to patch android apps

https://serializethoughts.com/2016/08/18/bypassing-ssl-pinning-in-android-applications/

**Comment by AlecAnthonyGarcia** [comment]
It's working great, cheers!

**Comment by wendal2841** [comment]
I open the file libliger.so across DA decompiler on Mac

I read your wiki  https://serializethoughts.com/2016/08/18/bypassing-ssl-pinning-in-android-applications/

can tell what to change in libliger.so to work in instagram sll UNPinning?
