### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by iwritecodetoo** [pouyadarabi/Instagram_SSL_Pinning#4]
Are there any specific requirements for this to work?

Just tried both the APK and downloading the original version and applying the patched file and couldn't get the proxy to see the requests.

Using android 7.

**Comment by pouyadarabi** [comment]
I just test new version on my own device (Android 7) and it's working fine!

You should install certificate on device 
and set proxy on it

First request will be displayed after a minute delay in proxy app so be patience

**Comment by rkzed94** [comment]
i got same issue, not working on nexus 5 android 5.1.1

**Comment by pouyadarabi** [comment]
All apks and so files are tested!

You should check these options:

- Run proxy on PC and make sure firewall not block it
- Set proxy ip and port on mobile device
- Install proxy certificate on mobile device
- Install Apk or move patched .so file
