### ISSUE TITLE
Patched as you did but still no luck?

### ISSUE THREAD

**Issue by VicoErv** [pouyadarabi/Instagram_SSL_Pinning#6]
![screenshot](https://image.prntscr.com/image/xQJcdLBpTpyhnIJVl3gYcA.png)

**Comment by pouyadarabi** [comment]
it's easy
just follow the function from start and patch jumps!
2 or 3 address need to be patched!

**Comment by VicoErv** [comment]
so it not just one that need to be patched? i will try. thank you
