### ISSUE TITLE
Works !!, But it doesn't work :/

### ISSUE THREAD

**Issue by u0pattern** [pouyadarabi/Instagram_SSL_Pinning#9]
<img src="https://b.top4top.net/p_7776kw8m1.jpg"><br>
It's works on `https://b.i.instagram.com/`<br>
But it doesn't work on `https://i.instagram.com/`<br>
<br><br>

Galaxy s5
5.0 Lolipop

Thx :)

**Comment by pouyadarabi** [comment]
Check patching steps again.
You can try new APK
And please note it will be shown with a minute delay after sending first request

**Comment by u0pattern** [comment]
Request HTTPSParse failed
doesn't work on `https://i.instagram.com/`

**Comment by learn-itnow** [comment]
I'm also getting same problem.
It works on https://b.i.instagram.com/

But it doesn't work on https://i.instagram.com/

**Comment by zek** [comment]
The main problem is instagram uses multiple http libraries. This shows only how to unpin libliger. You should also unpin the other libraries

**Comment by learn-itnow** [comment]
Do you have working apk that you can share which will work on https://i.instagram.com/ as well?

**Comment by huseyinalp-zz** [comment]
@zek bununla ilgili son bir durum bilgin varmı? elinde çalışan bir apk varsa iletişim kurarsan sevinirim.
tşkler.
